services:
  mysql:
    container_name: mysql_project1
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_DATABASE: bootcamp
    restart: unless-stopped

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: galkaev
    ports:
      - 8888:8080
    restart: unless-stopped

networks:
  mysql:
    driver: bridge

volumes:
  mysql: